 # dinky-server/portainer/docker-compose.yml
 services:
   portainer:
     image: portainer/portainer-ce:latest
     restart: unless-stopped
     ports:
       - "192.168.3.2:9000:9000"  # Portainer UI (internal access only)
       - "192.168.3.2:8000:8000" #Edge agent
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - portainer_data:/data
     networks:
       - traefik_network #Not needed for portainer, added if needed

 volumes:
   portainer_data:

 networks:
   traefik_network:
     external: true