receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  # Legacy endpoints
  otlp/legacy:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4316
      http:
        endpoint: 0.0.0.0:4319

processors:
  batch:
    send_batch_size: 10000
    timeout: 10s
  
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  
  resourcedetection:
    detectors: [env, system]
    timeout: 5s
  
  k8sattributes:
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.start_time

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: otelcol
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      resource:
        service.name: "service_name"
        service.instance.id: "service_instance_id"
      attributes:
        severity: "severity"
  
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  
  debug:
    verbosity: detailed
  
  otlphttp/pyroscope:
    endpoint: http://pyroscope:4040/ingest
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777
  
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp, otlp/legacy]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [otlp/tempo, debug]
    
    metrics:
      receivers: [otlp, otlp/legacy]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [prometheus, debug]
    
    logs:
      receivers: [otlp, otlp/legacy]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [loki, debug]
    
    profiles:
      receivers: [otlp, otlp/legacy]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [otlphttp/pyroscope, debug] 