services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "192.168.3.2:9000:9000"  # Portainer UI (internal access only)
      - "192.168.3.2:8000:8000" #Edge agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - traefik_network #Not needed for portainer, added if needed

  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "192.168.3.2:8080:8080"  # Traefik dashboard (internal access only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
    networks:
      - traefik_network
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml
      - cloudflared-data:/etc/cloudflared # Persist credentials
    env_file:
      - .env
    networks:
      - traefik_network
    depends_on:
      - traefik
      
  pihole:
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "192.168.3.2:8081:80/tcp"  # Web interface (changed to 8081 to avoid conflicts)
    env_file:
      - .env
    environment:
      TZ: 'Europe/Madrid'  # Timezone for Madrid
      WEBPASSWORD: '${PIHOLE_PASSWORD}'  # Get password from environment variable
      ServerIP: '192.168.3.2'  # Your server's IP address
      DNSMASQ_LISTENING: 'all'  # Listen on all interfaces
      DNS1: '1.1.1.1'  # Upstream DNS 1
      DNS2: '1.0.0.1'  # Upstream DNS 2
      # Add this to use Cloudflared for DNS-over-HTTPS if needed
      # PIHOLE_DNS_: 127.0.0.1#5053
    volumes:
      - pihole_data:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    networks:
      - traefik_network
    cap_add:
      - NET_ADMIN  # Required for Pi-hole to function correctly
    dns:
      - 127.0.0.1
      - 1.1.1.1

volumes:
  cloudflared-data:
  portainer_data:
  pihole_data:
  pihole_dnsmasq:

networks:
  traefik_network:
    external: true
