services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "192.168.3.2:9000:9000"  # Portainer UI (internal access only)
      - "192.168.3.2:8000:8000" #Edge agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    networks:
      - traefik_network #Not needed for portainer, added if needed
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "192.168.3.2:8080:8080"  # Traefik dashboard (internal access only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
    networks:
      - traefik_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml
      - cloudflared-data:/etc/cloudflared # Persist credentials
    env_file:
      - .env
    networks:
      - traefik_network
    depends_on:
      - traefik

volumes:
  cloudflared-data:
  portainer_data:

networks:
  traefik_network:
    external: true
