services:
  portainer:
    container_name: dinky-portainer
    image: portainer/portainer-ce:2.30.1
      - "9000:9000"  # Portainer UI (internal access only)
      - "8000:8000" #Edge agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data

  traefik:
    container_name: dinky-traefik
    image: traefik:v3.4.1
      - --configFile=/etc/traefik/traefik.yml
      - "8080:8080"  # Traefik dashboard (internal access only)
      - "80:80"  # HTTP (internal access only, cloudflared tunnels traffic)
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infrastructure/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./infrastructure/traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml

  cloudflared:
    container_name: dinky-cloudflared
    image: cloudflare/cloudflared:2025.5.0
      - ./infrastructure/cloudflared/config.yml:/etc/cloudflared/config.yml
      - cloudflared-data:/etc/cloudflared # Persist credentials
    env_file:
      - .env
      - traefik
      
  pihole:
    container_name: dinky-pihole
    image: pihole/pihole:2025.04.0
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"  # Web interface
    env_file:
      - .env
    environment:
      TZ: Europe/Madrid
      WEBPASSWORD: '${PIHOLE_PASSWORD}'
      ServerIP: '${SERVER_IP:-localhost}'
      DNSMASQ_LISTENING: 'all'
      DNS1: '1.1.1.1'  # Cloudflare DNS
      DNS2: '8.8.8.8'  # Google DNS
      - pihole_data:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1  # Use Cloudflare DNS directly
      - 8.8.8.8  # Use Google DNS as backup

  # Mail Services
  mail-server:
    container_name: dinky-mail-server
    build:
      context: ./services/mail-server
      dockerfile: Dockerfile
    hostname: ${MAIL_HOSTNAME:-mail.dinky.local}
    restart: unless-stopped
      - "25:25"   # SMTP (now accessible from other containers)
      - "587:587" # SMTP submission (internal access only)
      - mail-data:/var/mail
      - mail-logs:/var/log/mail
    environment:
      - TZ=Europe/Madrid
      - MAIL_DOMAIN=${MAIL_DOMAIN:-dinky.local}
      - MAIL_HOSTNAME=${MAIL_HOSTNAME:-mail.dinky.local}
      - DEFAULT_FROM=${DEFAULT_FROM:-noreply@dinky.local}
      - SMTP_RELAY_HOST=${SMTP_RELAY_HOST:-smtp.gmail.com}
      - SMTP_RELAY_PORT=${SMTP_RELAY_PORT:-587}
      - SMTP_RELAY_USERNAME=${SMTP_RELAY_USERNAME:-your-gmail-username@gmail.com}
      - SMTP_RELAY_PASSWORD=${SMTP_RELAY_PASSWORD:-your-gmail-app-password}
      - USE_TLS=${USE_TLS:-yes}
      - TLS_VERIFY=${TLS_VERIFY:-yes}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # LGTM Stack Components

  # Prometheus - Metrics collection and storage
  prometheus:
    image: prom/prometheus:v3.4.0
    container_name: dinky-prometheus
      - "${SERVER_IP:-localhost}:9090:9090"
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --storage.tsdb.retention.size=10GB
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --web.enable-admin-api
      - traefik

  # Alertmanager - Alert management and routing
  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: dinky-alertmanager
    restart: always
    ports:
      - "${SERVER_IP:-localhost}:9093:9093"
    environment:
      - DEFAULT_TO=${DEFAULT_TO:-admin@example.com}
    volumes:
      - ./monitoring/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      - --web.external-url=http://localhost:9093
      - --cluster.listen-address=
    networks:
      - traefik_network
      - mail-internal
    depends_on:
      - mail-server

  # Loki - Log aggregation
  loki:
    image: grafana/loki:3.5
    container_name: dinky-loki
      - "${SERVER_IP:-localhost}:3100:3100"
      - ./monitoring/loki:/etc/loki
      - loki_data:/loki

  # Promtail - Log collector for Loki
  promtail:
    image: grafana/promtail:3.5
    container_name: dinky-promtail
      - ./monitoring/promtail:/etc/promtail
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - loki

  # Tempo - Distributed tracing
  tempo:
    image: grafana/tempo:2.7.2
    container_name: dinky-tempo
      - "${SERVER_IP:-localhost}:3200:3200"  # Tempo receiver
      - ./monitoring/tempo:/etc/tempo
      - tempo_data:/var/tempo

  # Pyroscope - Continuous profiling
  pyroscope:
    image: grafana/pyroscope:1.13.4
    container_name: dinky-pyroscope
      - "${SERVER_IP:-localhost}:4040:4040"
      - ./monitoring/pyroscope:/etc/pyroscope
      - pyroscope_data:/var/lib/pyroscope

  # Grafana - Visualization
  grafana:
    image: grafana/grafana:12.0.1
    container_name: dinky-grafana
      - "${SERVER_IP:-localhost}:3000:3000"
      - ./monitoring/grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - prometheus
      - loki
      - tempo
      - pyroscope
    env_file:
      - .env

  # OpenTelemetry Collector - Telemetry collection and processing
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.127.0
    container_name: dinky-otel-collector
      - "${SERVER_IP:-localhost}:4317:4317"  # OTLP gRPC
      - "${SERVER_IP:-localhost}:4318:4318"  # OTLP HTTP
      - "${SERVER_IP:-localhost}:8888:8888"  # Metrics endpoint
      - ./monitoring/otel-collector:/etc/otel-collector
      - prometheus
      - loki
      - tempo
      - pyroscope


  # Container Metrics (added by monitoring setup)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: dinky-cadvisor
    privileged: true
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - "${SERVER_IP:-localhost}:8082:8080"  # cAdvisor web interface (avoid conflict with Traefik on 8080)
      - '--docker_only=true'
      - '--storage_duration=1m0s'
      - '--housekeeping_interval=10s'

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: dinky-node-exporter
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - "${SERVER_IP:-localhost}:9100:9100"

  cloudflared-data:
  grafana_data:
  pihole_data:
  pihole_dnsmasq:
  portainer_data:
  prometheus_data:
  loki_data:
  tempo_data:
  pyroscope_data:
  mail-data:
  mail-logs:

    external: true
    driver: bridge

x-common-variables: &common-variables
  DOMAIN_NAME: ${DOMAIN_NAME:-example.com}
  SERVER_IP: ${SERVER_IP:-localhost}
  TZ: ${TZ:-Europe/Madrid}
