services:
  looping-byte:
    image: ghcr.io/nahuelsantos/looping-byte:latest
    container_name: looping-byte
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.looopingbyte.rule=Host(`loopingbyte.com`) || Host(`www.loopingbyte.com`)"
      - "traefik.http.services.loopingbyte.loadbalancer.server.port=80" 
    networks:
      - traefik_network
    restart: unless-stopped
    environment:
      - NODE_ENV=production

networks:
  traefik_network:
    external: true