services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n 
    restart: unless-stopped 
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    # Optional: Add environment variables if needed
    # environment:
    #   - TZ=Europe/Madrid # Example: Set timezone based on your location (Barcelona)

volumes:
  n8n_data: {} 