log-level: info
server:
  http-listen-addr: ":4040"

analytics:
  disable-telemetry: true

database:
  path: /var/lib/pyroscope/data

retention:
  # Keep profiles for 30 days (consistent with Prometheus and Loki)
  profile-retention: 720h
  
cleanup:
  # Enable automatic cleanup of old profiles
  enable-cleanup: true
  cleanup-interval: 1h

scrape-configs:
  - job-name: pyroscope
    scrape-interval: 10s
    enabled-profiles: [cpu, mem, goroutines, mutex, block]
    static-configs:
      - application: pyroscope
        spy-name: gospy
        targets:
          - localhost:4040
        labels:
          service: pyroscope
          host: localhost

  - job-name: otel-collector
    scrape-interval: 10s
    enabled-profiles: [cpu, mem, goroutines, mutex, block]
    static-configs:
      - application: otel-collector
        spy-name: gospy
        targets:
          - otel-collector:4040
        labels:
          service: otel-collector
          host: otel-collector 