global:
  smtp_smarthost: 'mail-server:25'
  smtp_from: 'alerts@dinky.local'
  smtp_require_tls: false
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 24h
  receiver: 'default-alerts'
  routes:
    # Critical alerts - now also 1 hour repeat
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 1h
    # General service alerts
    - match_re:
        service: (website|cv-site|contact-api|loopingbyte-website)
      receiver: 'service-alerts'
      repeat_interval: 1h

receivers:
  - name: 'default-alerts'
    email_configs:
      - to: 'admin@dinky.local'
        headers:
          Subject: 'DINKY ALERT: {{ .GroupLabels.alertname }}'
  
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@dinky.local'
        headers:
          Subject: '🚨 CRITICAL DINKY ALERT: {{ .GroupLabels.alertname }}'

  - name: 'service-alerts'
    email_configs:
      - to: 'admin@dinky.local'
        headers:
          Subject: '⚠️ SERVICE ALERT: {{ .GroupLabels.alertname }} ({{ .CommonLabels.service }})'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance'] 