global:
  smtp_smarthost: 'mail-server:25'
  smtp_from: 'alerts@dinky.local'
  smtp_require_tls: false
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-alerts'
  routes:
    # Critical alerts go to both email and Discord immediately
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 30m
    # Website and service alerts
    - match_re:
        service: (website|cv-site|contact-api)
      receiver: 'service-alerts'
      repeat_interval: 15m

receivers:
  - name: 'default-alerts'
    email_configs:
      - to: 'admin@dinky.local'
        headers:
          Subject: 'DINKY ALERT: {{ .GroupLabels.alertname }}'
  
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@dinky.local'
        headers:
          Subject: '🚨 CRITICAL DINKY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          🚨 **CRITICAL ALERT** 🚨
          
          **Alert:** {{ .GroupLabels.alertname }}
          **Severity:** {{ .CommonLabels.severity }}
          **Service:** {{ .CommonLabels.service }}
          
          {{ range .Alerts }}
          **Summary:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
    # Discord webhook (uncomment and configure when ready)
    # webhook_configs:
    #   - url: '${DISCORD_WEBHOOK_URL}'
    #     send_resolved: true
    #     title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
    #     text: |
    #       **{{ .CommonLabels.service | toUpper }} ALERT**
    #       {{ range .Alerts }}{{ .Annotations.description }}{{ end }}

  - name: 'service-alerts'
    email_configs:
      - to: 'admin@dinky.local'
        headers:
          Subject: '⚠️ SERVICE ALERT: {{ .GroupLabels.alertname }} ({{ .CommonLabels.service }})'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance'] 