services:
  example-site:
    image: nginx:alpine
    container_name: example-site
    restart: unless-stopped
    ports:
      - "3002:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.example-site.rule=Host(`site.dinky.local`)"
      - "traefik.http.routers.example-site.service=example-site"
      - "traefik.http.services.example-site.loadbalancer.server.port=80"
    environment:
      - SITE_NAME=Example Site
      - VERSION=1.0.0

networks:
  traefik_network:
    external: true 