version: '3.8'

services:
  example-site:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true 