# dinky-server/traefik/docker-compose.yml
 services:
   traefik:
     image: traefik:v2.10
     restart: unless-stopped
     command:
       - --configFile=/etc/traefik/traefik.yml
     ports:
       - "192.168.3.2:8080:8080"  # Traefik dashboard (internal access only)
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - ./traefik.yml:/etc/traefik/traefik.yml:ro
       - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml
     networks:
       - traefik_network

 networks:
   traefik_network:
     external: true