# dinky-server/traefik/traefik.yml
api:
  dashboard: true
  insecure: true  # Enable the dashboard (we'll access it via internal IP)

entryPoints:
  web:
    address: :80
  metrics:
    address: :8082
  #websecure:
    #address: :443

providers:
  docker:
    exposedByDefault: false  # Only expose services with explicit labels
    network: traefik_network
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

log:
  level: DEBUG