# Production docker-compose file for mail services on Dinky

version: '3.8'

services:
  mail-server:
    image: ${REGISTRY}/${PROJECT}/mail-server:${TAG}
    container_name: ${PROJECT}_mail-server
    restart: unless-stopped
    build:
      context: ./mail-server
      dockerfile: Dockerfile.prod
    ports:
      - 25:25
      - 587:587
    volumes:
      - ./mail-server/data:/var/mail
      - ./mail-server/logs:/var/log
      - /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem:/etc/ssl/certs/cert.pem
      - /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem:/etc/ssl/private/key.pem
    environment:
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_HOSTNAME=mail.${MAIL_DOMAIN}
      - DEFAULT_USER=${MAIL_USER}
      - DEFAULT_PASS=${MAIL_PASSWORD}
      - DEFAULT_FROM=${DEFAULT_FROM}
      - RELAY_HOST=${SMTP_RELAY_HOST:-smtp.gmail.com}
      - RELAY_PORT=${SMTP_RELAY_PORT:-587}
      - RELAY_USERNAME=${SMTP_RELAY_USERNAME}
      - RELAY_PASSWORD=${SMTP_RELAY_PASSWORD}
    networks:
      - mail-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mail-api:
    image: ${REGISTRY}/${PROJECT}/mail-api:${TAG}
    container_name: ${PROJECT}_mail-api
    restart: unless-stopped
    build:
      context: ./mail-api
      dockerfile: Dockerfile.prod
      args:
        - API_URL=${API_URL}
    depends_on:
      - mail-server
    environment:
      - PORT=20001
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - MAIL_HOST=${MAIL_HOSTNAME:-mail.${MAIL_DOMAIN}}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASSWORD}
      - DEFAULT_FROM=${DEFAULT_FROM}
      - MAIL_SECURE=${MAIL_SECURE:-false}
      - FORWARD_EMAIL=${FORWARD_EMAIL}
    networks:
      - mail-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mail-data:
    driver: local
  mail-logs:
    driver: local

networks:
  mail-network:
    driver: bridge 