services:
  n8n:
    container_name: 8n8
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`nexus.loopingbyte.com`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=traefik_network"
    environment:
      - N8N_HOST=nexus.loopingbyte.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://nexus.yourdomain.com/
      - GENERIC_TIMEZONE=Europe/Madrid
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - traefik_network

volumes:
  n8n_data:
networks:
  traefik_network:
    external: true
