server:
  http_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317  # Internal port (mapped to 4316 externally)
        http:
          endpoint: 0.0.0.0:4318  # Not exposed externally - only through otel-collector
    zipkin:
      endpoint: 0.0.0.0:9411

# Ingestion limits and search
query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

ingester:
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000
    wal:
      path: /var/tempo/wal
    search:
      chunk_size_bytes: 1048576
      read_buffer_count: 8
      read_buffer_size_bytes: 4194304

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: dinky-server
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

compactor:
  compaction:
    block_retention: 168h      # Keep traces for 7 days (168 hours)
    compacted_block_retention: 1h
    max_block_bytes: 107374182400 