# dinky-server/cloudflared/config.yml
tunnel: ${TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json
logfile: /var/log/cloudflared.log
loglevel: info

ingress:
  - hostname: example.com
    service: http://traefik:80
  - hostname: www.example.com
    service: http://traefik:80
  - hostname: example-2.com
    service: http://traefik:80
  - hostname: www.example-2.com
    service: http://traefik:80
  - service: http_status:404 #Default