global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: 'dinky-server'
    replica: 'primary'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
    metrics_path: /metrics

  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
    
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "pyroscope"
    static_configs:
      - targets: ["pyroscope:4040"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"] 

  # Docker Service Discovery for containers with monitoring labels
  - job_name: 'docker-services'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      # Only scrape containers with prometheus.scrape=true label
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        action: keep
        regex: true
      
      # Set job name from prometheus.job label if present
      - source_labels: [__meta_docker_container_label_prometheus_job]
        target_label: job
        regex: (.+)
      
      # If no job label, use container name as job (remove leading slash)
      - source_labels: [__meta_docker_container_name]
        target_label: job
        regex: /(.+)
        replacement: ${1}
      
      # Set instance from container name (remove leading slash)  
      - source_labels: [__meta_docker_container_name]
        target_label: instance
        regex: /(.+)
        replacement: ${1}
      
      # Set custom metrics path if specified
      - source_labels: [__meta_docker_container_label_prometheus_path]
        target_label: __metrics_path__
        regex: (.+)
      
      # Set default metrics path if not specified
      - target_label: __metrics_path__
        replacement: /metrics
      
      # Build address from container name and custom port
      - source_labels: [__meta_docker_container_name, __meta_docker_container_label_prometheus_port]
        target_label: __address__
        regex: /([^;]+);(.+)
        replacement: ${1}:${2}

  # Blackbox exporter for HTTP probing
  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['blackbox-exporter:9115']

  # HTTP probes via Docker discovery for static sites (internal container probing)
  - job_name: 'docker-http-probes'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    relabel_configs:
      # Only probe containers with prometheus.probe=http label
      - source_labels: [__meta_docker_container_label_prometheus_probe]
        action: keep
        regex: http
      # Build target URL with port from label (remove leading slash from container name)
      - source_labels: [__meta_docker_container_name, __meta_docker_container_label_prometheus_port]
        target_label: __param_target
        regex: /([^;]+);(.+)
        replacement: http://${1}:${2}
      # Use the target URL as instance name
      - source_labels: [__param_target]
        target_label: instance
      # Point to blackbox exporter
      - target_label: __address__
        replacement: blackbox-exporter:9115
      # Set job name from container label
      - source_labels: [__meta_docker_container_label_prometheus_job]
        target_label: job
        regex: (.+)
        replacement: ${1}-http-internal

  # Nginx Prometheus Exporter - Scrape converted nginx metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  # External website monitoring (real user-facing URLs)
  - job_name: 'website-probes'
    static_configs:
      - targets:
        - https://nahuelsantos.com
        - https://cv.nahuelsantos.com  
        - https://loopingbyte.com
    metrics_path: /probe
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115