global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: 'dinky-server'
    replica: 'primary'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8084"]
    metrics_path: /metrics

  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
    
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "pyroscope"
    static_configs:
      - targets: ["pyroscope:4040"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"] 

  - job_name: "argus"
    static_configs:
      - targets: ["argus:3001"]