version: '3.8'

services:
  example-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true 